accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

book_review_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("books.urls")),
]

books/urls.py
from django.urls import path
from .views import BookListView, BookDetailView, BookCreateView, BookUpdateView, BookDeleteView

urlpatterns = [
path("book/new/", BookCreateView.as_view(), name="book_new"),
path("book/<int:pk>/", BookDetailView.as_view(), name="book_detail"),
path("book/<int:pk>/edit/", BookUpdateView.as_view(), name="book_update"),
path("book/<int:pk>/delete/", BookDeleteView.as_view(),name="book_delete"),
path("", BookListView.as_view(), name="home"),
]

accounts/models.py
from django.db import models

# Create your models here.

books/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=120)
    author = models.CharField(max_length=50)
    synopsis = models.TextField()
    year_published = models.IntegerField()
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})
    
    @property
    def number_of_reviews(self):
        return Review.objects.filter(book=self).count()

class Review(models.Model):
    rate_choices = (
        (1,1),
        (2,2),
        (3,3),
        (4,4),
        (5,5)
    )
    stars = models.IntegerField(choices=rate_choices, default=1)
    title = models.CharField(max_length=100)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    content = models.TextField()
    user = models.CharField(max_length=20)
    
    def __str__(self):
        return str(self.title)
    
    def get_absolute_url(self):
        return reverse("book_list")

books/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("user", "title", "stars", "content")

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

books/views.py
from django.shortcuts import render
from .models import Book, Review
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, DetailView, FormView, View, CreateView, UpdateView, DeleteView
from .forms import ReviewForm
from django.urls import reverse_lazy, reverse
# Create your views here.

class BookListView(ListView):
    model = Book
    template_name = "home.html"

class ReviewGet(DetailView): # new
    model = Book
    template_name = "book_detail.html"
    
    def get_context_data(self, **kwargs): # new
        context = super().get_context_data(**kwargs)
        context["form"] = ReviewForm()
        return context

class BookDetailView(View): # new
    def get(self, request, *args, **kwargs):
        view = ReviewGet.as_view()
        return view(request, *args, **kwargs)
    def post(self, request, *args, **kwargs):
        view = ReviewPost.as_view()
        return view(request, *args, **kwargs)

class ReviewPost(SingleObjectMixin, FormView): # new
    model = Book
    form_class = ReviewForm
    template_name = "book_detail.html"
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)
    def form_valid(self, form):
        review = form.save(commit=False)
        review.book = self.object
        review.user = review.user
        review.save()
        return super().form_valid(form)
    def get_success_url(self):
        book = self.object
        return reverse("book_detail", kwargs={"pk": book.pk})

class BookCreateView(LoginRequiredMixin, CreateView): # new
    model = Book
    template_name = "book_new.html"
    fields = ["title", "author", "synopsis", "year_published"]
    

class BookUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Book
    template_name = "book_update.html"
    fields = ["title", "author", "synopsis", "year_published"]
    permission_required = 'user.is_staff'
    
    def test_func(self): # new
        obj = self.get_object()
        return obj.author == self.request.user

class BookDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Book
    template_name = "book_delete.html"
    success_url = reverse_lazy("home")
    permission_required = 'user.is_staff'
    
    def test_func(self): # new
        obj = self.get_object()
        return obj.author == self.request.user

books/templates/base.html
<!-- templates/base.html -->
{% load static %}
<html>
    <head>
        <title>Book Reviews</title>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
            rel="stylesheet">
        <link href="{% static 'css/base.css' %}" rel="stylesheet" s>
    </head>
    <body>
        <div>
            <header>
                <div class="nav-left">
                    <h1><a href="{% url 'home' %}">Book Reviews!</a></h1>
                </div>
                {% if user.is_authenticated%}
                <div class="nav-right">
                    <a href="{% url 'book_new' %}">+ Add a New Book</a>
                </div>
                {% endif%}
            </header>
            {% if user.is_authenticated %}
                <p>Hi {{ user.username }}!</p>
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit">Log Out</button>
                </form>
            {% else %}
                <p>You are not logged in.</p>
                <a href="{% url 'login' %}">Log In</a>|
                <a href="{% url 'signup' %}">Sign Up</a>
            {% endif %}
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

books/templates/book_delete.html
<!-- templates/book_delete.html -->
{% extends "base.html" %}
{% block content %}
<h1>Remove book</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

books/templates/book_detail.html
<!-- templates/book_update.html -->
{% extends "base.html" %}
{% load crispy_forms_tags %}
    {% block content %}
        <div class="book-entry">
            <h2>{{ object.title }}</h2>
            <p>Year Published: {{ object.year_published }}</p>
            <p>Synopsis: {{ object.synopsis }}</p>  
        </div>
        {% if user.is_staff %}
            <a href="{% url 'book_update' book.pk %}">+ Update Book Information</a>
            <a href="{% url 'book_delete' book.pk %}">+ Remove Book</a>
        {% endif %}
        <hr>
        <h4>Reviews</h4>
        {% for review in book.review_set.all %}
        <p>{{ review.user }} </p>
        <p><b>Title:</b> {{ review }} </p>
        <p><b>Rating:</b> {{ review.stars }}/5</p>
        <p><b>Review:</b></p>
        <p>{{ review.content }}</p>
        <p>---------------------</p>
        {% endfor %}
        <hr>
        <h4>Add a review</h4>
            <form action="" method="post">{% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-success ml-2" type="submit">Save</button>
            </form>
    {% endblock content %}

books/templates/book_new.html
{% extends "base.html" %}
    {% block content %}
        <h1>New book</h1>
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save">
            </form>
{% endblock content %}

books/templates/book_update.html
<!-- templates/book_update.html -->
{% extends "base.html" %}
    {% block content %}
        <h1>Edit post</h1>
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Update">
            </form>
{% endblock content %}

books/templates/home.html
<!-- templates/home.html -->
{% extends "base.html" %}
    {% block content %}
        {% for book in book_list %}
            <div class="book-entry">
                <h2><a href="{% url 'book_detail' book.pk %}">{{ book.title }}</a></h2>
                <p>Author: {{ book.author }}</p>
            </div>
        {% endfor %}
    {% endblock content %}